package HighlandsCoffee.form;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import HighlandsCoffee.DBConnection; 

public class TrangChu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TrangChu.class.getName());

    private String role;
    private String staffId;

    public TrangChu() {
        initComponents();
    }
    public TrangChu(String role, String staffId) {
        initComponents();
        this.role = role;
        this.staffId = staffId;
        setLocationRelativeTo(null);
        lblUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
    }
    public void setLoginContext(String fullname, String role){
        lblUsername.setText("Xin chào, "+fullname+" ["+role+"]");
        if(!role.equalsIgnoreCase("Admin")){
            btnNhanVien.setVisible(false);
            btnThongKe.setVisible(false);
        }
        pnlMenu.revalidate();
        pnlMenu.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnBanHang = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnBanAn = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));

        pnlHeader.setBackground(new java.awt.Color(100, 21, 21));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        pnlHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlHeader.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pnlHeader.setPreferredSize(new java.awt.Dimension(800, 80));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HighlandsCoffee/images/logo.png"))); // NOI18N
        pnlHeader.add(jLabel1, java.awt.BorderLayout.WEST);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HỆ THỐNG QUẢN LÝ");
        pnlHeader.add(jLabel2, java.awt.BorderLayout.CENTER);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Xin chào, ");
        pnlHeader.add(lblUsername, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.NORTH);

        pnlMenu.setBackground(new java.awt.Color(245, 245, 245));
        pnlMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 1, 10));
        pnlMenu.setPreferredSize(new java.awt.Dimension(200, 100));
        pnlMenu.setLayout(new javax.swing.BoxLayout(pnlMenu, javax.swing.BoxLayout.Y_AXIS));

        btnBanHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBanHang.setForeground(new java.awt.Color(100, 21, 21));
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 10));
        btnBanHang.setBorderPainted(false);
        btnBanHang.setContentAreaFilled(false);
        btnBanHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBanHang.setMargin(new java.awt.Insets(2, 20, 3, 14));
        pnlMenu.add(btnBanHang);

        btnSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(100, 21, 21));
        btnSanPham.setText("SẢN PHẨM");
        btnSanPham.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 10));
        btnSanPham.setBorderPainted(false);
        btnSanPham.setContentAreaFilled(false);
        btnSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSanPham.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnSanPham.addActionListener(this::btnSanPhamActionPerformed);
        pnlMenu.add(btnSanPham);

        btnBanAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBanAn.setForeground(new java.awt.Color(100, 21, 21));
        btnBanAn.setText("BÀN ĂN");
        btnBanAn.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 10));
        btnBanAn.setBorderPainted(false);
        btnBanAn.setContentAreaFilled(false);
        btnBanAn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBanAn.setMargin(new java.awt.Insets(2, 20, 3, 14));
        pnlMenu.add(btnBanAn);

        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(100, 21, 21));
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 10));
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.setContentAreaFilled(false);
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVien.setMargin(new java.awt.Insets(2, 20, 3, 14));
        pnlMenu.add(btnNhanVien);

        btnHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(100, 21, 21));
        btnHoaDon.setText("HÓA ĐƠN");
        btnHoaDon.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 10));
        btnHoaDon.setBorderPainted(false);
        btnHoaDon.setContentAreaFilled(false);
        btnHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHoaDon.setMargin(new java.awt.Insets(2, 20, 3, 14));
        pnlMenu.add(btnHoaDon);

        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(100, 21, 21));
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 10));
        btnThongKe.setBorderPainted(false);
        btnThongKe.setContentAreaFilled(false);
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongKe.setMargin(new java.awt.Insets(2, 20, 3, 14));
        pnlMenu.add(btnThongKe);

        getContentPane().add(pnlMenu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>                        

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TrangChu().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBanAn;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration                   
}
